# Generated by Django 5.0.1 on 2024-01-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transactions_is_complated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
