# Generated by Django 5.0.1 on 2024-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баланс'),
        ),
    ]
