# Generated by Django 5.0.1 on 2024-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс'),
        ),
    ]
