# Generated by Django 5.0.1 on 2024-01-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кошелек'),
        ),
    ]
