# Generated by Django 5.0.1 on 2024-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=4, verbose_name='Баланс'),
        ),
    ]
