# Generated by Django 5.0.1 on 2024-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_username', models.CharField(max_length=255, verbose_name='Получатель')),
                ('from_username', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('amount', models.SmallIntegerField(default=0, verbose_name='Кол-во coins')),
            ],
            options={
                'verbose_name': 'Коин',
                'verbose_name_plural': 'Коины',
            },
        ),
    ]
