# Generated by Django 5.0.1 on 2024-01-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_usercoins_delete_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoins',
            options={'verbose_name': 'Коин', 'verbose_name_plural': 'Коины'},
        ),
    ]
